# Generated by Django 3.2.4 on 2021-06-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default='', max_length=50)),
                ('Course_Number', models.IntegerField()),
                ('Instructor_Name', models.CharField(blank=True, default='', max_length=75)),
                ('Duration', models.FloatField()),
            ],
        ),
    ]
